name: RNN

# ---------------------------------------------------------------------------- #
#                                    datast                                    #
# ---------------------------------------------------------------------------- #
interactive: False

training_data_description: ''
dataset_normalizer: 'scale'  # or scale / standardize
n_trials_training: ''
n_trials_test: ''

single_trial_mode: False  # for debugging


# ---------------------------------------------------------------------------- #
#                                    params                                    #
# ---------------------------------------------------------------------------- #

# ----------------------------------- Task ----------------------------------- #
BATCH: 64
T: 2000
dt: 5
tau: 100

# --------------------------------- Training --------------------------------- #
EPOCHS: 350  # ! EPOCHS
steps_per_epoch: 16

lr_schedule:
      boundaries: [10, 500, 1200]
      values: [0.01, 0.001, 0.0001, 0.00001]
      name: 'PiecewiseConstantDecay'

optimizer: 'Adam'
clipvalue: null
amsgrad: True
sample_weight: null

# ----------------------------------- Model ---------------------------------- #
layers:
  - 
        name: simpleRNN
        units: 5
        activation: 'tanh'
        stateful: False
        trainable: True
  - 
        name: dense
        units: 2
        activation: 'tanh'
        stateful: null
        trainable: False

loss: 'mse'